### ISSUE TITLE
Missing dependencies in requirements.txt?

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/esi-leap#138]
The `Containerfile` explicitly installs `mysql-connector` and `pymysql`. Are these requirements for `esi-leap`? Should they be listed in `requirements.txt`?

**Comment by tzumainn** [comment]
Huh - actually, I don't think they are, and they don't seem to be installed in the MOC ESI instance either. @skanthed do you remember if there were errors if these packages weren't installed?

**Comment by skanthed** [comment]
@tzumainn If mysql-connector and pymysql were not installed and there were no errors reported during the execution of esi-leap,

**Comment by tzumainn** [comment]
@skanthed ah, I don't think they were actually required then; would it be possible to remove them from the Containerfile?

**Comment by skanthed** [comment]
@tzumainn I mentioned it because I was not able to connect to a database or create a schema, Let me double-check and test few things. Suppose it works the same way. I will remove it.

**Comment by skanthed** [comment]
yes, even I think so. But I can double-check and test it again.

**Comment by samuel-zuk** [comment]
I believe they need to be installed for the `esi-leap-dbsync` commands to work properly-- I don't think they should be added to the `requirements.txt` file, since the core ESI-Leap functionality (i.e. the API & manager) works without them, but if the `dbsync` commands fail because `mysql-connector` and `pymysql` aren't installed, that might be worth mentioning in the README, I think.

**Comment by larsks** [comment]
I think that if the modules are required for the code to run, they should be included in `requirements.txt`, or the database functionality should be split into a separate package that can be installed independently.

**Comment by tzumainn** [comment]
I agree with lars - these should be added.

**Comment by skanthed** [comment]
https://github.com/CCI-MOC/esi-leap/pull/157
