### ISSUE TITLE
Create email notifications when a lease is close to expiration

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi-leap#149]
Notify users (projects?) when their lease is about to go away so they don't panic.

**Comment by joachimweyl** [comment]
@DanNiESh do we plan to finish this in this sprint or shall we push it off to the next sprint?

**Comment by DanNiESh** [comment]
Please push it off to the next sprint. This task should be done quickly

**Comment by DanNiESh** [comment]
https://github.com/CCI-MOC/esi-leap/pull/150
